# Site settings
baseURL = "http://www.marco-sanna.de"
languageCode = "en-US"
title = "Marco Sanna"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2025 Wichtel Akademy RÃ¸stlandet"

[params]
  favicon = "favicon.ico"
  [params.visual]
    [params.visual.image]
      enable = true
      file = "images/northern-lights.jpg"
      position = "center center"